services:
  - type: web
    name: games-demo-app
    env: ruby
    plan: free
    buildCommand: "bundle install && rails db:migrate"
    startCommand: "rails server -b 0.0.0.0 -p 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: games_demo_app
          property: connectionString

databases:
  - name: games_demo_app
    plan: free
